name: Run Tests on Merge to Master

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      SECRET_KEY: ${{ env.SECRET_KEY }}
      POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
      POSTGRES_USER: ${{ env.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      SSLMODE: ${{ vars.SSLMODE }}
      TIMEZONE: ${{ vars.TIMEZONE }}
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
        
    - name: Debug
      run: |
        echo "POSTGRES_HOST: $POSTGRES_HOST"
        echo "POSTGRES_USER: $POSTGRES_USER"
        echo "POSTGRES_PASSWORD: $POSTGRES_PASSWORD"
        echo "POSTGRES_DB: $POSTGRES_DB"
        echo "POSTGRES_PORT: $POSTGRES_PORT"
        echo "SSLMODE: $SSLMODE"
        echo "TIMEZONE: $TIMEZONE"

    - name: Run Tests
      run: go test -v ./...
      
    - name: Merge to main if tests pass
      if: success()
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git merge ${{ github.event.before }} --no-ff --no-edit
        git push
